language: dart
dist: xenial
addons:
  apt:
    packages:
    - lib32stdc++6
branches:
  only:
  - master
install:
  - git clone https://github.com/flutter/flutter.git -b beta
  - ./flutter/bin/flutter doctor
  - ./flutter/bin/flutter packages get
script:
  - ./flutter/bin/flutter test
cache:
  directories:
  - $HOME/.pub-cache
